version: '3'
services:
  web-app:
    build: web-app
    #   dockerfile: Dockerfile
    #   context: ../lemon-mart
    # ports:
    #   - '8080:3000'
    ports:
      - '8080:80'
    links:
      - server
    depends_on:
      - server

  server:
    build: server
    env_file: .env
    ports:
      - '3000:3000'
    links:
      - database
    depends_on:
      - database

  database:
    image: excellalabs/mongo:4.1.13
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - '/tmp/minimal-mean-db:/data/db'
