// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/errorhandler/errorhandler.d.ts
// Type definitions for errorhandler
// Project: https://github.com/expressjs/errorhandler
// Definitions by: Santi Albo <https://github.com/santialbo/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


declare module "errorhandler" {
    import * as express from 'express';

    function errorHandler(options?: errorHandler.Options): express.ErrorRequestHandler;

    namespace errorHandler {
        interface LoggingCallback {
            (err: Error, str: string, req: express.Request, res: express.Response): void;
        }

        interface Options {
            /**
             * Defaults to true.
             *
             * Possible values:
             *   true       : Log errors using console.error(str).
             *   false      : Only send the error back in the response.
             *   A function : pass the error to a function for handling.
             */
            log: boolean | LoggingCallback;
        }
    }

    export = errorHandler;
}